name: Java CI/CD

on:
  push:
    branches: [ "main", "update" ]
  pull_request:
    branches: [ "main", "update" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar projeto
        run: javac -d out $(find src -name "*.java")

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Simular Deploy
        run: |
          echo "Iniciando deploy..."
          mkdir -p deploy
          cp -r out/* deploy/
          echo "Deploy realizado com sucesso!"
