name: Java CI/CD

on:
  push:
    branches: [ "main", "update" ]
  pull_request:
    branches: [ "main", "update" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar projeto
        run: javac -d out $(find src -name "*.java")

      - name: Salvar artefatos compilados
        uses: actions/upload-artifact@v4
        with:
          name: arquivos-compilados
          path: out/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Baixar artefatos compilados
        uses: actions/download-artifact@v4
        with:
          name: arquivos-compilados
          path: out/

      - name: Simular Deploy
        run: |
          echo "Iniciando deploy..."
          mkdir -p deploy
          cp -r out/* deploy/
          echo "Deploy realizado com sucesso!"

  notify:
    runs-on: ubuntu-latest
    needs: [build, deploy]
    if: always() # Executa mesmo se outros jobs falharem
    steps:
      - name: Notificar Discord
        uses: Ilshidur/action-discord@0.3.1
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: |
            {
              "username": "GitHub Actions",
              "avatar_url": "https://github.com/github.png",
              "content": "🚀 **CI/CD Status**\nRepositório: ${{ github.repository }}\nBranch: ${{ github.ref }}\nAutor: ${{ github.actor }}\nStatus: ${{ job.status }}\nDetalhes: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }